import style from './Home.module.css'

function Home() {
    return(
        <div className={style.contentStyle}>
            <h1>Home</h1>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
            <div>teste</div>
        </div>
    )
}

export default Home